routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Front\HomeController;
use App\Http\Controllers\Front\DriversController;
use App\Http\Controllers\Front\AutosController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {          
    return redirect()->route('drivers.index'); 
})->name('home');

Route::resource('drivers', DriversController::class)->only(['index','create','store']);

Route::resource('autos', AutosController::class)->only(['index','create','store']);

app/Models/Auto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use \DateTimeInterface;

class Auto extends Model
{
    use HasFactory;

    protected $dates = [
        'created_at',
        'updated_at',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'type',
        'cap_tractor',
        'special_truck',
        'little_truck',
        'car',
        'semitraier',
        'trailer',
        'make',
        'model',
        'vin',
        'first_registration',
        'purchase_date',
    ];

    public function documents()
    {
        return $this->morphMany(Uploads::class, 'uploadsable');
    }

}

app/Models/Driver.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use \DateTimeInterface;

class Driver extends Model
{
    use HasFactory;

    protected $dates = [
        'created_at',
        'updated_at',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'social_security_number',
    ];


}

app/Models/Uploads.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Uploads extends Model
{

	protected $appends = ['name','file_url','size'];

    protected $fillable = ['path','extension', 'upload_type', 'expires_at'];

    public function getNameAttribute()
    {
        return substr($this->path, strpos($this->path, "/") + 1);
    }

    public function getSizeAttribute()
    {
        try {
        	if($this->path && \Storage::disk('public')->exists($this->path)){
                return \File::size(public_path('storage/'.$this->path));
            }
        } catch (Exception $e) {
            return 0;
        }
        return 0;
    }

    public function getFileUrlAttribute()
    {
    	$MediaImage = '';
    	if($this->path && \Storage::disk('public')->exists($this->path)){
            $MediaImage = asset('storage/'.$this->path);
        }
        return $MediaImage;
    }

    /**
     * Get all of the models that own uploads.
     */
    public function uploadsable()
    {
        return $this->morphTo();
    }
    
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Front/AutosController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Front\Auto\StoreRequest;
use Symfony\Component\HttpFoundation\Response;
use App\Models\Auto;
use App\Models\Uploads;
use Validator;

class AutosController extends Controller
{
    public function __construct()
    {
        
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $autos = Auto::all();
        return view('front.autos.index',compact('autos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $autoTypes = config('constants.auto_types');
        $documentTypes = config('constants.auto_document_types');
        return view('front.autos.create',compact(['autoTypes','documentTypes']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        $inputs = $request->all();
        $inputs['purchase_date'] = date('Y-m-d',strtotime($inputs['purchase_date']));
        $auto = Auto::create($inputs);
        if($auto){
            if($request->hasFile('documents') && count($request->documents) > 0){
                foreach ($request->file('documents') as $file_type => $file) {
                    $this->uploadDocument($auto, $file,'auto-documents',$file_type);
                }
            }
        }
        return redirect()->route('autos.index')->with('success',trans('cruds.auto.title_singular')." ".trans('panel.add_succes'));
    }

    public function uploadDocument($directory, $file, $folder,$file_type){
        $upload               = new Uploads; 
        $upload->path         = $file->store($folder, 'public');
        $upload->extension    = $file->getClientOriginalExtension();        
        $upload->upload_type  = $file_type;        
        $upload->expires_at   = date('Y-m-d',strtotime(request()->expiries[$file_type]));        

        $response             = $directory->documents()->save($upload);  
        return true;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Auto $auto)
    {
        // return view('admin.articles.show', compact('article'));
    }

    
}

app/Http/Controllers/Front/DriversController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Models\Driver;
use Validator;

class DriversController extends Controller
{
    public function __construct()
    {
        
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $drivers = Driver::all();
        return view('front.drivers.index',compact('drivers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('front.drivers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $driver = Driver::create($request->all());
        return redirect()->route('home');
    }

    

}

app/Http/Controllers/Front/HomeController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {  
        return view('welcome');
    }


    
}

resources/views/front/autos/create.blade.php
@extends('layouts.app')

@section('styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.css" />
@endsection

@section('content')
    <div class="modal-dialog-lg">
        <div class="modal-content">
            <div class="modal-header justify-content-center">
                <h2 class="modal-title">{{ trans('panel.add') }} {{ trans('cruds.auto.title_singular') }}</h2>
            </div>
            <form id="createAutoForm" action="{{ route('autos.store') }}" role="form" files=true enctype="multipart/form-data" method="post">
                <div class="modal-body">
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="input-group input-group-cust">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-car"></i></span>
                                    </div>
                                    {!! Form::select('type',$autoTypes,null, ['placeholder' => 'Select Auto Type','class'=>'form-control','required'=>'required']) !!}
                                </div>
                                @if($errors->has('type'))
                                <div class="help-block text-danger">
                                    {{ $errors->first('type') }}
                                </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="input-group input-group-cust">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-car"></i></span>
                                    </div>
                                    {!! Form::text('make',null,['placeholder' => 'Make','class'=>'form-control','required'=>'required']) !!}
                                </div>
                                @if($errors->has('make'))
                                <div class="help-block text-danger">
                                    {{ $errors->first('make') }}
                                </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="input-group input-group-cust">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-car"></i></span>
                                    </div>
                                    {!! Form::selectYear('model', 1990, date('Y'),null,['placeholder' => 'Select Model','class'=>'form-control','required'=>'required']) !!}
                                </div>
                                @if($errors->has('model'))
                                <div class="help-block text-danger">
                                    {{ $errors->first('model') }}
                                </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="input-group input-group-cust">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-car"></i></span>
                                    </div>
                                    {!! Form::text('vin',null,['placeholder' => 'VIN','class'=>'form-control','required'=>'required']) !!}
                                </div>
                                @if($errors->has('vin'))
                                <div class="help-block text-danger">
                                    {{ $errors->first('vin') }}
                                </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="input-group input-group-cust">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-car"></i></span>
                                    </div>
                                    {!! Form::text('first_registration',null,['placeholder' => 'First Registration','class'=>'form-control','required'=>'required']) !!}
                                </div>
                                @if($errors->has('first_registration'))
                                <div class="help-block text-danger">
                                    {{ $errors->first('first_registration') }}
                                </div>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="input-group input-group-cust">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-calendar-day"></i></span>
                                    </div>
                                    {!! Form::text('purchase_date',null,['placeholder' => 'Purchase Date','class'=>'form-control purchase_date','required'=>'required','autoComplete'=>'off']) !!}
                                </div>
                                @if($errors->has('purchase_date'))
                                <div class="help-block text-danger">
                                    {{ $errors->first('purchase_date') }}
                                </div>
                                @endif
                            </div>
                        </div>
                    </div>

                    <hr>
                    <div class="documents">
                        <div class="document-heading">
                            <h4>Upload Documents</h4>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                @foreach($documentTypes as $key => $documentType)
                                    <div class="row">
                                        <div class="col-md-6">  
                                            <div class="row">
                                                <label class="control-label col-sm-5">{{ $documentType }}</label>
                                                <div class="col-sm-7"> 
                                                    <div class="form-group input-group-cust"> 
                                                        <input type="file" class="form-control-file" accept="image/png,image/jpg,image/jpeg,application/pdf,application/docx" name="documents[{{$key}}]" required />
                                                    </div>
                                                    @if($errors->has('documents.'.$key))
                                                    <div class="help-block text-danger">
                                                        {{ $errors->first('documents.'.$key) }}
                                                    </div>
                                                    @endif
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="row">
                                                <label class="control-label col-sm-3">Expiry Date</label>
                                                <div class="col-sm-9"> 
                                                    <div class="form-group input-group-cust"> 
                                                        {!! Form::text('expiries['.$key.']',null,['placeholder' => 'Expiry Date','class'=>'form-control datepicker','required'=>'required','autoComplete'=>'off']) !!}
                                                    </div>
                                                    @if($errors->has('expiries.'.$key))
                                                    <div class="help-block text-danger">
                                                        {{ $errors->first('expiries.'.$key) }}
                                                    </div>
                                                    @endif
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer text-center justify-content-center">
                    <button type="submit" class="btn btn-success btn-lg">Save</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
@parent
<script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('.purchase_date').datepicker({
            "format" : "dd-MM-YYYY",
            "endDate" : new Date(),
            'autoHide': true,
        });

        $('.datepicker').datepicker({
            "format" : "dd-MM-YYYY",
            "startDate" : new Date(),
            'autoHide': true,
        });
        
        /* Form Validate */
		$.validator.addMethod('filesize', function (value, element, param) {
			console.log(element.files[0].size);
			return this.optional(element) || (element.files[0].size <= param)
		}, 'File size must be less than {0}');

        $('#createAutoForm').validate({
           onfocusout: false,
           errorPlacement: function(label, element) {
                console.log($(element).is('file'));
                label.addClass('help-block validation-error');
                if ($(element).is('select') && $(element).hasClass('select2')) {
                    label.insertAfter(element.siblings('.select2'));
                } else if ($(element).is('select')) {
                    label.insertAfter(element.parents('.input-group-cust'));
                }else if ($(element).is('file')) {
                    label.insertAfter(element);
                } else {
                    label.insertAfter(element.parents('.input-group-cust'));
                }
           },
           rules: {
              "type": "required",
              "make": "required",
              "model": "required",
              "vin": "required",
              "first_registration": "required",
              "purchase_date": "required",
			  "documents[]": {
                "required": true,
                "extension": "png,jpg,jpeg,pdf,docx",
                "maxsize": 50,
              },
              "expiries[]": "required",
           },
           messages: {
              "type": "Please select auto type",
              "make": "Please fill make",
              "model": "Please fill model",
              "vin": "Please enter vin number",
              "first_registration": "Please fill first registration",
              "purchase_date": "Please fill purchase date",
			  "documents[]": {
                   "required": "Please upload document",
                   "extension": "Please upload valid file",
                   "maxsize": "Size wrong",
               },
              "expiries[]": "Please fill expiry date of document",
           }
        });
    });
</script>
@endsection

resources/views/front/autos/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
      	<div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
	      	<div class="card">
	          <div class="card-header card-header-primary">
	            <h4 class="card-title text-center">
	              {{ trans('cruds.auto.title_singular') }} {{ trans('panel.list') }}
	            </h4>

	            <div class="card-body">
		            <div class="row justify-content-end">
		              <a class="btn btn-primary m-2" href="{{ route('autos.create') }}" data-toggle="tooltip" rel="tooltip" data-placement="top" title="{{ trans('global.add') }}"> Add Auto </a>
		            </div>
		            <br />
		            <div class="table-responsive">
		            	<table class="table table-striped table-bordered dt-responsive">
		            		<thead>
						      <tr>
						        <th>#</th>
						        <th>{{ trans('cruds.auto.fields.type') }}</th>
						        <th>{{ trans('cruds.auto.fields.make') }}</th>
						        <th>{{ trans('cruds.auto.fields.model') }}</th>
						        <th>{{ trans('cruds.auto.fields.vin') }}</th>
						        <th>{{ trans('cruds.auto.fields.purchase_date') }}</th>
						        <th>{{ trans('cruds.auto.fields.created_at') }}</th>
						      </tr>
						    </thead>
						    <tbody>
						    	@if($autos->count() > 0)
						    		@foreach($autos as $key => $auto)
								    	<tr>
								        	<td>{{ $key+1 }}</td>
								        	<td>{{ config('constants.auto_types')[$auto->type] ?? "" }}</td>
								        	<td>{{ $auto->make ?? "" }}</td>
								        	<td>{{ $auto->model ?? "" }}</td>
								        	<td>{{ $auto->vin ?? "" }}</td>
								        	<td>{{ date('d-M-Y',strtotime($auto->purchase_date)) ?? "" }}</td>
								        	<td>{{ date('d-M-Y',strtotime($auto->created_at)) ?? "" }}</td>
								      	</tr>
						      		@endforeach
						      	@else
						      		<tr class="text-center">
						      			<td colspan="7">No auto available</td>
						      		</tr>
						      	@endif
						    </tbody>
		            	</table>
		            </div>
	          </div>
	      	</div>
      	</div>
  </div>
@endsection

resources/views/front/drivers/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header justify-content-center">
                <h2 class="modal-title">{{ trans('panel.add') }} {{ trans('cruds.driver.title_singular') }}</h2>
            </div>
            <form id="createDriverForm"  action="{{ route('drivers.store') }}" method="POST" role="form">
                <div class="modal-body">
                    @csrf
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-user"></i></span>
                            </div>
                            <input type="text" name="first_name" class="form-control" placeholder="First Name" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-user"></i></span>
                            </div>
                            <input type="text" name="last_name" class="form-control" placeholder="Last Name" />
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-lock"></i></span>
                            </div>
                            <input type="text" name="social_security_number" class="form-control" placeholder="Social Security Number" />
                        </div>
                    </div>
                    
                </div>
                <div class="modal-footer text-center justify-content-center">
                    <button type="submit" class="btn btn-success btn-lg">Save</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
@parent
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('#createDriverForm').validate({
           onfocusout: false,
           errorPlacement: function(label, element) {
                label.addClass('help-block validation-error');
                if ($(element).is('select') && $(element).hasClass('select2')) {
                    label.insertAfter(element.siblings('.select2'));
                } else if ($(element).is('select')) {
                    label.insertAfter(element.parents('.input-group'));
                } else {
                    label.insertAfter(element.parents('.input-group'));
                }
           },
           rules: {
              "first_name": "required",
              "last_name": "required",
              "social_security_number": "required",
           },
           messages: {
              "first_name": "Please fill first name",
              "last_name": "Please fill last name",
              "social_security_number": "Please fill social security number",
           }
        });
    });
</script>
@endsection

resources/views/front/drivers/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
      	<div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
	      	<div class="card">
	          <div class="card-header card-header-primary">
	            <h4 class="card-title text-center">
	              {{ trans('cruds.driver.title_singular') }} {{ trans('panel.list') }}
	            </h4>

	            <div class="card-body">
		            <div class="row justify-content-end">
		              <a class="btn btn-primary m-2" href="{{ route('drivers.create') }}" data-toggle="tooltip" rel="tooltip" data-placement="top" title="{{ trans('global.add') }}"> Add Driver </a>
		            </div>
		            <br />
		            <div class="table-responsive">
		            	<table class="table table-striped table-bordered dt-responsive">
		            		<thead>
						      <tr>
						      	<th>#</th>
						        <th>{{ trans('cruds.driver.fields.first_name') }}</th>
						        <th>{{ trans('cruds.driver.fields.last_name') }}</th>
						        <th>{{ trans('cruds.driver.fields.social_security_number') }}</th>
						      </tr>
						    </thead>
						    <tbody>
						    	@if($drivers->count() > 0)
						    		@foreach($drivers as $key => $driver)
								    	<tr>
								    		<td>{{ $key+1 }}</td>
								        	<td>{{ $driver->first_name ?? "" }}</td>
								        	<td>{{ $driver->last_name ?? "" }}</td>
								        	<td>{{ $driver->social_security_number ?? "" }}</td>
								      	</tr>
						      		@endforeach
						      	@else
						      		<tr class="text-center">
						      			<td colspan="4">No driver available</td>
						      		</tr>
						      	@endif
						    </tbody>
		            	</table>
		            </div>
	          </div>
	      	</div>
      	</div>
  </div>
@endsection

resources/views/layouts/app.blade.php
 <!DOCTYPE html>
<html lang="en">
    <head>
        <title>Auto Parts</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
        <link rel="stylesheet" href="{{ asset('assets/front/style.css') }}">
        @yield('styles')
    </head>
    <body>

        <div class="page-wrapper compact-wrapper" id="pageWrapper">
            @include('partials.header')
          <!-- Main content -->
            <section class="content py-4" style="padding-top: 30px">
                <div class="page-body">
                    <div class="container">
                        @if(session('success'))                            
                            <div class="row mb-2">
                                <div class="col-lg-12">
                                    <div class="alert alert-success" role="alert">{{ session('success') }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                          <span class="text-white" aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                </div>
                            </div>                
                        @endif

                        @yield("content")
                    </div>
                </div>
            </section>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js"></script>
        @yield('scripts')
    </body>
</html>

resources/views/partials/header.blade.php
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item {{ request()->is('drivers*') ? 'active' : '' }}">
      <a class="nav-link" href="{{ route('drivers.index') }}">{{ trans('cruds.driver.title') }}</a>
    </li>
    <li class="nav-item {{ request()->is('autos*') ? 'active' : '' }}">
      <a class="nav-link" href="{{ route('autos.index') }}">{{ trans('cruds.auto.title') }}</a>
    </li>
  </ul>
</nav>